### ISSUE TITLE
TestIngester::test_ingester Failed while testing local version of kowalski

### ISSUE THREAD

**Issue by viraj21197** [dmitryduev/kowalski#88] opened 2021-03-09 19:30 UTC
**Describe the bug**
When testing a local version of Kowalski (using `./kowalski.py test`), the `test_ingester.py::TestIngester::test_ingester - assert 0 == 313` test fails. 
The cause of this could possibly be the following failures on connecting to the Kafka cluster (see screenshot, full log attached)-
1. `Message delivery failed: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}`

 2.` Message delivery failed: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}%3|1615087455.390|FAIL|rdkafka#producer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 15 identical error(s) suppressed)`

**To Reproduce**
 - Execute `./kowalski.py test`

**Expected behavior**
 - All tests should pass, and the different mongo-db collections should be populated with a few ZTF alerts.

**Screenshots**
<img width="623" alt="Screen Shot 2021-03-09 at 11 38 12 AM" src="https://user-images.githubusercontent.com/20256511/110528503-12621180-80cd-11eb-9739-f62edc32b6ba.png">
<img width="618" alt="Screen Shot 2021-03-09 at 11 41 38 AM" src="https://user-images.githubusercontent.com/20256511/110528561-20b02d80-80cd-11eb-9c75-8c9702416e8c.png">

**Platform information:**
  - macOS Catalina 10.15.7
  - anaconda3 version 3.8.5
  - docker version 20.10.5
  - docker-compose version 1.28.5

**Additional context**
Full log of the tests
[kowalski_test_log.log](https://github.com/dmitryduev/kowalski/files/6111046/kowalski_test_log.log)

**Comment by dmitryduev** [comment] 2021-04-12 19:43
Can't reproduce. @viraj21197 have you tried this again with the latest master?

**Comment by dmitryduev** [comment] 2021-04-20 19:33
Still can't reproduce, closing as stalled.

**Closed by dmitryduev** 2021-04-20 19:33 UTC
Labels: bug
